{{- if .Values.config }}
apiVersion: v1
data:
  config.yml: |-
{{- if .Values.config.exposer }}
    exposer: {{ .Values.config.exposer  }}
{{- end }}
{{- if .Values.config.domain }}
    domain: {{ .Values.config.domain }}
{{- end }}
{{- if .Values.config.pathMode }}
    path-mode: {{ .Values.config.pathMode }}
{{- end }}
{{- if .Values.config.ingressClass }}
    ingress-class: {{ .Values.config.ingressClass }}
{{- end }}
{{- if .Values.config.urltemplate }}
    urltemplate: {{ .Values.config.urltemplate }}
{{- end }}
    http: {{ .Values.config.http | default true }}
    tls-acme: {{ .Values.config.tlsacme | default false  }}
{{- if .Values.config.tlsSecretName }}
    tls-secret-name: {{ .Values.config.tlsSecretName }}
{{- end }}
{{- if .Values.config.extravalues }}
{{ toYaml .Values.config.extravalues | indent 4 }}
{{- end }}
kind: ConfigMap
metadata:
  name: exposecontroller
{{- end }}
